apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modia-robot-api
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  port: 7070
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://modia-robot-api.intern.dev.nav.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      external:
        - host: nom-api.intern.dev.nav.no
        - host: pdl-api.dev-fss-pub.nais.io
        - host: saf.dev-fss-pub.nais.io
        - host: digdir-krr-proxy.intern.dev.nav.no
        - host: sokos-utbetaldata.dev-fss-pub.nais.io
        - host: sf-henvendelse-api-proxy.dev-fss-pub.nais.io
        - host: sokos-kontoregister-person.intern.dev.nav.no
        - host: kodeverk-api.nav.no
      rules:
        - application: veilarboppfolging
          namespace: poao
        - application: syfooversiktsrv
          namespace: teamsykefravr
        - application: logging
          namespace: nais-system
    inbound:
      rules:
        - application: rpa-medlemskap-og-avgift
          namespace: team-rpa
          cluster: dev-fss
        - application: rpa-saf-tiltakspenger
          namespace: team-rpa
          cluster: dev-fss
        - application: ida
          cluster: prod-fss
          namespace: traktor
        - application: rpa-nav-okonomi-stonad
          cluster: dev-fss
          namespace: team-rpa-nos
        - application: rpa-nos-robot1
          cluster: dev-fss
          namespace: team-rpa
        - application: arbeid-og-ytelser
          cluster: dev-fss
          namespace: team-rpa
  env:
    - name: IDENT_ALLOW_LIST
      value: "R158611,R154727,R156418,R158345,R158346,R160569,R165950,R165951,R165952,R150818,R150819,R155645,R162552,Z994123,Z990351,Z992779,Z990949,Z990467,Z991629,Z990237,Z994673,Z994818,Z990715,Z990715,Z990467,Z990715,Z990122,Z993068,Z994484,Z994019,Z990122,Z990125"
    - name: OPPFOLGING_URL
      value: "http://veilarboppfolging.poao/veilarboppfolging/api"
    - name: OPPFOLGING_SCOPE
      value: "dev-gcp:poao:veilarboppfolging"
    - name: SYFO_URL
      value: "http://syfooversiktsrv.teamsykefravr/api"
    - name: SYFO_SCOPE
      value: "dev-gcp:teamsykefravr:syfooversiktsrv"
    - name: NOM_URL
      value: "https://nom-api.intern.dev.nav.no"
    - name: NOM_SCOPE
      value: "dev-gcp:nom:nom-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "dev-fss:pdl:pdl-api"
    - name: SAF_URL
      value: "https://saf-q2.dev-fss-pub.nais.io/graphql"
    - name: SAF_SCOPE
      value: "dev-fss:teamdokumenthandtering:saf"
    - name: SKRIVESTOTTE_URL
      value: "https://modiapersonoversikt-skrivestotte.intern.dev.nav.no"
    - name: DIGDIR_KRR_URL
      value: "https://digdir-krr-proxy.intern.dev.nav.no/"
    - name: DIGDIR_KRR_SCOPE
      value: "dev-gcp:team-rocket:digdir-krr-proxy"
    - name: UTBETALDATA_SOKOS_URL
      value: "https://sokos-utbetaldata.dev-fss-pub.nais.io/utbetaldata/api"
    - name: UTBETAL_SOKOS_SCOPE
      value: "dev-fss:okonomi:sokos-utbetaldata"
    - name: SF_HENVENDELSE_URL
      value: "https://sf-henvendelse-api-proxy.dev-fss-pub.nais.io/api"
    - name: SF_HENVENDELSE_SCOPE
      value: "dev-fss:teamnks:sf-henvendelse-api-proxy"
    - name: KONTOREGISTER_REST_URL
      value: "https://sokos-kontoregister-person.intern.dev.nav.no/api/system"
    - name: KONTOREGISTER_SCOPE
      value: "dev-gcp:okonomi:sokos-kontoregister-person"
    - name: KODEVERK_URL
      value: "https://kodeverk-api.nav.no"
    - name: KODEVERK_SCOPE
      value: "dev-gcp:team-rocket:kodeverk-api"
