apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modia-robot-api
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 7070
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://modia-robot-api.intern.nav.no
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 65
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvmodiabrukerdialog
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/prod/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: IDENT_ALLOW_LIST
      value: "Z999999"
    - name: SECURITYTOKENSERVICE_URL
      value: "https://sts.adeo.no/SecurityTokenServiceProvider/"
    - name: ISSO_JWKS_URL
      value: "https://isso.adeo.no/isso/oauth2/connect/jwk_uri"
    - name: OPPFOLGING_URL
      value: "https://veilarboppfolging.nais.adeo.no/veilarboppfolging/api"
    - name: OPPFOLGING_SCOPE
      value: "prod-fss:pto:veilarboppfolging"
    - name: TPS_PERSONV3_URL
      value: "https://app.adeo.no/tpsws-aura/ws/Person/v3"
    - name: NOM_URL
      value: "https://nom-api.intern.nav.no"
    - name: OPPFOLGING_SCOPE
      value: "prod-gcp:nom:nom-api"
    - name: SKRIVESTOTTE_URL
      value: "https://app.adeo.no/modiapersonoversikt-skrivestotte"
    - name: DIGDIR_KRR_URL
      value: "https://digdir-krr-proxy.intern.nav.no"
    - name: DIGDIR_KRR_SCOPE
      value: "prod-gcp:team-rocket:digdir-krr-proxy"