apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modia-robot-api
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 7070
  webproxy: true
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://modia-robot-api.intern.nav.no
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 65
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvmodiarobotapi
        mountPath: /var/run/secrets/nais.io/srvmodiarobotapi
      - kvPath: /serviceuser/data/prod/srvmodiabrukerdialog
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/prod/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: IDENT_ALLOW_LIST
      value: "R154727,R156418,R158345,R158346,R160569,R165950,R165951,R165952,R150818,R150819,R155645,R162552,D159483,U143410"
    - name: SECURITYTOKENSERVICE_URL
      value: "https://sts.adeo.no/SecurityTokenServiceProvider/"
    - name: ISSO_JWKS_URL
      value: "https://isso.adeo.no/isso/oauth2/connect/jwk_uri"
    - name: OPPFOLGING_URL
      value: "https://veilarboppfolging.nais.adeo.no/veilarboppfolging/api"
    - name: OPPFOLGING_SCOPE
      value: "prod-fss:pto:veilarboppfolging"
    - name: TPS_PERSONV3_URL
      value: "https://app.adeo.no/tpsws-aura/ws/Person/v3"
    - name: NOM_URL
      value: "https://nom-api.intern.nav.no"
    - name: NOM_SCOPE
      value: "prod-gcp:nom:nom-api"
    - name: PDL_URL
      value: "https://pdl-api.nais.adeo.no/graphql"
    - name: PDL_SCOPE
      value: "prod-fss:pdl:pdl-api"
    - name: SAF_URL
      value: "https://saf.nais.adeo.no/graphql"
    - name: SAF_SCOPE
      value: "prod-fss:teamdokumenthandtering:saf"
    - name: SKRIVESTOTTE_URL
      value: "https://app.adeo.no/modiapersonoversikt-skrivestotte"
    - name: DIGDIR_KRR_URL
      value: "https://digdir-krr-proxy.intern.nav.no"
    - name: DIGDIR_KRR_SCOPE
      value: "prod-gcp:team-rocket:digdir-krr-proxy"
    - name: UTBETALDATA_SOKOS_URL
      value: "https://sokos-utbetaldata.intern.nav.no/utbetaldata/api"
    - name: UTBETAL_SOKOS_SCOPE
      value: "prod-fss:okonomi:sokos-utbetaldata"
    - name: SF_HENVENDELSE_URL
      value: "https://sf-henvendelse.intern.nav.no/api"
    - name: SF_HENVENDELSE_SCOPE
      value: "prod-fss:teamcrm:sf-henvendelse"
    - name: CXF_SECURE_LOG
      value: "enabled"