apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modia-robot-api
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  port: 7070
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://modia-robot-api.intern.nav.no
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 65
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      external:
        - host: nom-api.intern.prod.nav.no
        - host: pdl-api.prod-fss-pub.nais.io
        - host: saf.prod-fss-pub.nais.io
        - host: digdir-krr-proxy.intern.nav.no
        - host: sokos-utbetaldata.prod-fss-pub.nais.io
        - host: sf-henvendelse-api-proxy.prod-fss-pub.nais.io
        - host: sokos-kontoregister-person.intern.nav.no
      rules:
        - application: veilarboppfolging
          namespace: poao
        - application: syfooversiktsrv
          namespace: teamsykefravr
    inbound:
      rules:
        - application: rpa-medlemskap-og-avgift
          namespace: team-rpa
          cluster: prod-fss
        - application: rpa-ata-fordele-gosys-oppgaver
          namespace: team-rpa
          cluster: prod-fss
        - application: ida
          namespace: traktor
          cluster: prod-fss
        - application: rpa-nav-okonomi-stonad
          namespace: team-rpa-nos
          cluster: prod-fss
        - application: rpa-nos-modia
          namespace: team-rpa
          cluster: prod-fss
        - application: arbeid-og-ytelser
          cluster: prod-fss
          namespace: team-rpa
        - application: rpa-nos-robot
          cluster: prod-fss
          namespace: team-rpa
  env:
    - name: IDENT_ALLOW_LIST
      value: "R156347,R158611,R154727,R156418,R158345,R158346,R160569,R165950,R165951,R165952,R150818,R150819,R155645,R162552,D159483,U143410,R172987,R150819,R150818,R162552,R155645,R150819,R150818,R162552,R155645"
    - name: OPPFOLGING_URL
      value: "http://veilarboppfolging.poao/veilarboppfolging/api"
    - name: OPPFOLGING_SCOPE
      value: "prod-gcp:poao:veilarboppfolging"
    - name: SYFO_URL
      value: "http://syfooversiktsrv.teamsykefravr/api"
    - name: SYFO_SCOPE
      value: "prod-gcp:teamsykefravr:syfooversiktsrv"
    - name: NOM_URL
      value: "https://nom-api.intern.nav.no"
    - name: NOM_SCOPE
      value: "prod-gcp:nom:nom-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "prod-fss:pdl:pdl-api"
    - name: SAF_URL
      value: "https://saf.prod-fss-pub.nais.io/graphql"
    - name: SAF_SCOPE
      value: "prod-fss:teamdokumenthandtering:saf"
    - name: SKRIVESTOTTE_URL
      value: "https://modiapersonoversikt-skrivestotte.intern.nav.no"
    - name: DIGDIR_KRR_URL
      value: "https://digdir-krr-proxy.intern.nav.no/"
    - name: DIGDIR_KRR_SCOPE
      value: "prod-gcp:team-rocket:digdir-krr-proxy"
    - name: UTBETALDATA_SOKOS_URL
      value: "https://sokos-utbetaldata.prod-fss-pub.nais.io/utbetaldata/api"
    - name: UTBETAL_SOKOS_SCOPE
      value: "prod-fss:okonomi:sokos-utbetaldata"
    - name: SF_HENVENDELSE_URL
      value: "https://sf-henvendelse-api-proxy.prod-fss-pub.nais.io/api"
    - name: SF_HENVENDELSE_SCOPE
      value: "prod-fss:teamnks:sf-henvendelse-api-proxy"
    - name: KONTOREGISTER_REST_URL
      value: "https://sokos-kontoregister-person.intern.nav.no/api/system"
    - name: KONTOREGISTER_SCOPE
      value: "prod-gcp:okonomi:sokos-kontoregister-person"
    - name: CXF_SECURE_LOG
      value: "enabled"
