apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modia-robot-api
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 7070
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://modia-robot-api.intern.nav.no
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 65
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
